import fs from 'node:fs/promises'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import os from 'node:os'

const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'native-port-'))
const allContracts = JSON.parse(await fs.readFile('component-contracts.json', 'utf8'))
const fixtureContracts = path.join(tmp, 'component-contracts.json')
await fs.writeFile(fixtureContracts, JSON.stringify(allContracts.filter((contract) => contract.name === 'dialog')))
execFileSync(process.execPath, ['scripts/convert-shadcn-html.mjs', 'tests/fixtures/shadcn-html', tmp, fixtureContracts], { stdio: 'inherit' })
const css = await fs.readFile(path.join(tmp, 'dialog/dialog.css'), 'utf8')
const html = await fs.readFile(path.join(tmp, 'dialog/index.html'), 'utf8')
const fragment = await fs.readFile(path.join(tmp, 'dialog/component.html'), 'utf8')
const index = await fs.readFile(path.join(tmp, 'index.html'), 'utf8')
const catalog = await fs.readFile(path.join(tmp, 'COMPONENT_MINIMUM_STYLES.md'), 'utf8')
const report = JSON.parse(await fs.readFile(path.join(tmp, 'conversion-report.json'), 'utf8'))
assert.match(css, /position: fixed/)
assert.match(css, /max-inline-size: calc\(100vw - 2rem\)/)
assert.match(css, /overflow: auto/)
assert.match(css, /max-width: 28rem/)
assert.match(css, /display: grid/)
assert.match(css, /grid-template-columns: 1fr auto/)
assert.doesNotMatch(css, /background: red/)
assert.match(css, /border: none/)
assert.doesNotMatch(css, /border-radius/)
assert.doesNotMatch(css, /background-color/)
assert.doesNotMatch(css, /(?:^|\n)\s*color:/)
assert.doesNotMatch(css, /box-shadow/)
assert.match(css, /font-family: "A;B", system-ui/)
assert.match(css, /font-size: 0.875rem/)
assert.match(css, /font-weight: 600/)
assert.match(css, /line-height: 1.5/)
assert.match(css, /background: url\("a;b"\)/)
assert.match(css, /transition: opacity 150ms/)
assert.match(css, /\.dialog\[data-state="open"\]/)
assert.match(css, /transform: scale\(1\)/)
assert.match(css, /transition: transform 150ms ease/)
assert.match(css, /textarea:is\(\[data-state="open"\], \[data-state="closed"\]\)/)
assert.match(css, /input:where\(:focus, :hover\)/)
assert.match(css, /textarea \{/)
assert.doesNotMatch(css, /textareainput/)
assert.match(css, /animation: fade-in 150ms ease/)
assert.match(css, /text-decoration: underline/)
assert.doesNotMatch(css, /outline: 2px solid red/)
assert.match(css, /outline-offset: 2px/)
assert.doesNotMatch(css, /accent-color: red/)
assert.doesNotMatch(css, /outline-color: color-mix\(in srgb, red 50%, blue\)/)
assert.match(css, /\.btn-group \{/)
assert.match(css, /\.switch-thumb \{/)
assert.match(css, /\.radio-group \{/)
assert.doesNotMatch(css, /button-group/)
assert.doesNotMatch(css, /switch-itembutton|radio-groupinput/)
assert.match(css, /button\.foo:hover/)
assert.match(css, /input\[type="checkbox"\]:checked/)
assert.match(css, /input\[type="radio"\]:focus-visible/)
assert.match(css, /input\[type="checkbox"\]\[role="switch"\]:disabled/)
assert.match(css, /content: "var\(--ignored, red\)"/)
assert.doesNotMatch(css, /text-muted-foreground/)
assert.doesNotMatch(css, /\\!bg-red-500/)
assert.doesNotMatch(css, /var\(--(?:popover|radius|border)\b|--(?:popover|radius|border)\b/)
assert.doesNotMatch(css, /:root|\.dark|\.bg-red-500/)
assert.doesNotMatch(css, /\.text-red-500/)
assert.match(css, /padding: 0/)
assert.match(html, /class="btn"/)
assert.match(html, /data-variant="default"/)
assert.match(html, /class="checkbox"/)
assert.match(html, /class="radio"/)
assert.match(html, /class="switch"/)
assert.match(html, /class="checkbox-item"/)
assert.match(html, /class="radio-group"/)
assert.match(html, /class="switch-item"/)
assert.match(html, /<button/)
assert.match(fragment, /<button/)
assert.match(index, /<ul[\s\S]*<li[\s\S]*<a href="dialog\/index\.html">dialog<\/a>/)
assert.match(index, /native-ui\/core\.css/)
assert.match(html, /class="container readable stack"/)
assert.match(catalog, /\| \[dialog\]\(\.\/dialog\/index\.html\) \|/)
assert.equal(report.count, 1)
assert.equal(report.source, 'tests/fixtures/shadcn-html')
assert.equal(path.isAbsolute(report.source), false)
assert.equal(report.components[0].contract.primitive, 'dialog')
assert.equal(report.components[0].contract.cssPolicy, 'native-visual-denylist')
assert.doesNotMatch(index, /<style|components\/dialog|vendor|shadcn/)
assert.doesNotMatch(html, /<style|vendor|shadcn|documentation|sidebar/)
assert.doesNotMatch(html, /\sstyle=/)
assert.match(html, /Example 1/)
assert.match(html, /href="\.\/dialog\.css"/)
assert.match(html, /<script type="module" src="\.\/dialog\.js"><\/script>/)
assert.match(html, /href="\.\.\/native-ui\/core\.css"/)
assert.match(html, /href="\.\.\/native-ui\/layout\.css"/)
assert.match(html, /href="\.\.\/native-ui\/components\.css"/)
assert.ok(await fs.stat(path.join(tmp, 'native-ui/core.css')))
assert.rejects(fs.stat(path.join(tmp, 'theme')))
assert.doesNotMatch(fragment, /Tooltip text/)
assert.rejects(fs.stat(path.join(tmp, 'README.md')))

const fullTmp = await fs.mkdtemp(path.join(os.tmpdir(), 'native-boundary-'))
execFileSync(process.execPath, ['scripts/convert-shadcn-html.mjs', 'vendor/shadcn-html', fullTmp], { stdio: 'inherit' })
assert.rejects(fs.stat(path.join(fullTmp, 'accordion/accordion.js')))
assert.match(await fs.readFile(path.join(fullTmp, 'carousel/carousel.js'), 'utf8'), /from "\.\.\/native-ui\/behavior\/carousel\.js"/)
assert.doesNotMatch(await fs.readFile(path.join(fullTmp, 'carousel/carousel.js'), 'utf8'), /MutationObserver|Adapted upstream behavior/)
assert.ok(await fs.stat(path.join(fullTmp, 'native-ui/behavior/tabs.js')))
assert.match(await fs.readFile(path.join(fullTmp, 'dialog/index.html'), 'utf8'), /data-dialog-trigger="dialog-example-1-my-dialog"/)
assert.match(await fs.readFile(path.join(fullTmp, 'dialog/index.html'), 'utf8'), /<script type="module" src="\.\/dialog\.js"><\/script>/)
assert.match(await fs.readFile(path.join(fullTmp, 'command/index.html'), 'utf8'), /data-command-trigger="command-example-1-cmd"/)
assert.match(await fs.readFile(path.join(fullTmp, 'command/index.html'), 'utf8'), /<script type="module" src="\.\/command\.js"><\/script>/)
assert.match(await fs.readFile(path.join(fullTmp, 'combobox/index.html'), 'utf8'), /<button[^>]*popovertarget="combobox-example-1-framework-popover"/s)
assert.doesNotMatch(await fs.readFile(path.join(fullTmp, 'combobox/index.html'), 'utf8'), /<input[^>]*popovertarget=/s)
assert.doesNotMatch(await fs.readFile(path.join(fullTmp, 'icon/index.html'), 'utf8'), /data-lucide=/)
assert.match(await fs.readFile(path.join(fullTmp, 'icon/index.html'), 'utf8'), /<svg[^>]*>\s*<(?:path|circle)/)

const cwdIndependentTmp = await fs.mkdtemp(path.join(os.tmpdir(), 'native-cwd-'))
execFileSync(process.execPath, [
  new URL('../scripts/convert-shadcn-html.mjs', import.meta.url).pathname,
  'vendor/shadcn-html', cwdIndependentTmp, 'component-contracts.json',
], { cwd: os.tmpdir(), stdio: 'inherit' })
assert.ok(await fs.stat(path.join(cwdIndependentTmp, 'dialog/dialog.js')))
console.log('converter: ok')
